### ISSUE TITLE
Feature Request: Linear Advance Calibration

### ISSUE THREAD

**Issue by jledgett** [Snapmaker/SnapmakerController-IDEX#11]
Can we get a guided Linear Advance Calibration added to the firmware (similar to the vibration compensation calibration)?

**Comment by apphead** [comment]
I think there's a misunderstanding. Initial poster asked for a _guided_ LA calibration that would run on the android touchscreen.

Configuring LA in firmware should be possible now, assuming that M900 is supported by Marlin blend of J1.

A good how-to, including default values, for various materials/nozzle sizes can be found here https://help.prusa3d.com/article/linear-advance_2252

It's almost slicer agnostic....

**Comment by 747lulu747** [comment]
Hi jledgett, you can refer to this page: [(https://marlinfw.org/tools/lin_advance/k-factor.html)]
