### ISSUE TITLE
Feature request: extrusion calibration

### ISSUE THREAD

**Issue by obertini78** [Snapmaker/SnapmakerController-IDEX#16]
Asking for a possibility to adjust/calibrate extrusion steps of both extruders. A guided/semi-automated calibration would be nice.
Reason: ensuring no over/under extrusion could be the root cause of print quality issues.
Thanks for considering this.

**Comment by 747lulu747** [comment]
Here is a detailed tutorial：https://all3dp.com/2/extruder-calibration-calibrate-e-steps/#i-10-6-set-a-new-steps-per-millimeter-value. You can do it on the J1 as J1 support all the gcodes relate to extrusion calibration.
