### ISSUE TITLE
Feature Request: Enable emergency stop

### ISSUE THREAD

**Issue by evilC** [Snapmaker/SnapmakerController-IDEX#5]
# 🐞 feature request
The `M112` (Emergency stop) command does not work.

### Describe the solution you'd like?
Enable `EMERGENCY_PARSER` in `Configuration.h`

**Comment by 747lulu747** [comment]
Hi evilC,

In fact, J1 supports M112, this is the output information of executing M112 on J1：
`echo:M112 Shutdown
Error:Printer halted. kill() called!`
