### ISSUE TITLE
While connected via OctoPrint, Control menu on printer screen is non-functional and breaks OctoPrint

### ISSUE THREAD

**Issue by evilC** [Snapmaker/SnapmakerController-IDEX#9]
Edit: I realized of course that this is not related to Cura - where do I post issues related to the firmware? The [Snapmaker2-Controller](https://github.com/Snapmaker/Snapmaker2-Controller) repo?

1. Connect to printer using OctoPrint **but do not start a job via octoprint, or do anything - octoprint is not in control of the printer at all**
2. Press `Control` on the printer's screen
3. Controls are non functional (eg cannot move axes, or load/unload filament) , and at this point, octoprint throws the following error:
```Your printer's firmware reported an error. Due to that OctoPrint will disconnect. Reported error: heve no cmd_set:1, cmd_id:162```
4. Re-connecting octoprint is then no longer possible until you reboot the machine

I can do this just fine with my other marlin printers. eg I can connect octoprint, then use the menu on the printer itself to load / unload filament etc, and it does not mess with the octoprint connection.

**Comment by 747lulu747** [comment]
Have fixed this by commit id: 85904090539c15a3b4d1d6f9499b73ba12f4ea0e.
We are goting to close this isssue.
